version: 0.1

phases:
  install:
    commands:
      - echo Installing code...
  secrets-manager:
    password: secret-id:password
  post_build:
    commands:
      - echo Performing Test with 'password'
artifacts:
  files:
    - '**/*'
