version: 0.1

env:
  secrets-manager:
    PASSWORD: $SECRETS_ID:password


phases:
  install:
    commands:
      - echo Installing code...
  post_build:
    commands:
      - echo Performing Test with $PASSWORD
artifacts:
  files:
    - '**/*'
