version: "3.4"

services: 
  app:
    image: dmodules/django_docker_beanstalk:1.0
    hostname: app

  nginx:
      image: nginx
      hostname: nginx
      ports:
        - "80:80"
      volumes:
        - ./config/nginx:/etc/nginx/conf.d
      depends_on:
        - app
