version: 0.1

env:
  secrets-manager:
    password: arn:aws:secretsmanager:us-east-1:757537583185:secret:password-YyyAIi


phases:
  install:
    commands:
      - echo Installing code...
  post_build:
    commands:
      - echo Performing Test with $password
artifacts:
  files:
    - '**/*'
