version: 0.1

env:
  password: $Test
    

phases:
  install:
    commands:
      - echo Installing code...
  post_build:
    commands:
      - echo Performing Test with $password
artifacts:
  files:
    - '**/*'
