version: 0.1

phases:
  install:
    commands:
      - echo Installing code...
  post_build:
    commands:
      - echo Performing Test with $password 123
      - echo db_password=$password > test.conf
      - echo db=123 >> test.conf
artifacts:
  files:
    - '**/*'
