version: 0.1

phases:
  install:
    commands:
      - echo Installing code...
  post_build:
    commands:
      - echo Performing Test with $password
      - echo $password > test.conf
artifacts:
  files:
    - '**/*'
